# 应用名称
# 没有mybatis-plus多数据源情况配置
spring:
  application:
    name: springboot-mybatis-plus
  profiles:
    active: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/linjiashop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
#    username: root
#    password:

# mybatis-plus多数据源情况配置
  datasource:
    dynamic:
      primary: master # 设置默认的数据源或数据源组，默认值为master
      strict: false # 严格匹配数据源，默认为false，true未匹配到数据源时抛出异常，false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/linjiashop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
          username: root
          password: root
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/linjiashop_2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
          username: root
          password: root
      # 使用hikariCP替代druid
      hikari:
        max-lifetime: 1800000
        connection-timeout: 5000
        idle-timeout: 3600000
        max-pool-size: 12
        min-idle: 4
        connection-test-query: /**ping*/

server:
  port: 9099

mybatis-plus:
  # 日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名（since 3.3.0，配置后可以忽略不配置步骤二）
      logic-delete-value: 1 # 逻辑已删除值（默认为1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为0）
      # 或者使用 注解
#      @TableLogic
#      private Integer isDelete;