spring:
  application:
    name: springboot-kafka
  # kafka properties
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      type: batch
      missing-topics-fatal: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "test-group"
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.lwc.springboot.kafka.dto
#            type:
#              mapping: dto:com.lwc.springboot.kafka.dto.KafkaMessageDTO

